### ISSUE TITLE
提问报错：model.model_error.ModelLoadError: Failed to load model: model info file not found

### ISSUE THREAD

**Issue by Rongliangshi** [BinNong/meet-libai#4]
ic| message: '您好'
ic| question_type: <QuestionType.HELLO: 7>
2024-06-24 17:06:08.108 | INFO     | model.graph_entity.search_model:reload:75 - loading entity searcher [version:0]
Traceback (most recent call last):
  File "D:\Program Files\anaconda\envs\myenv\lib\site-packages\gradio\queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "D:\Program Files\anaconda\envs\myenv\lib\site-packages\gradio\route_utils.py", line 235, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\Program Files\anaconda\envs\myenv\lib\site-packages\gradio\blocks.py", line 1627, in process_api
    result = await self.call_function(
  File "D:\Program Files\anaconda\envs\myenv\lib\site-packages\gradio\blocks.py", line 1185, in call_function
    prediction = await utils.async_iteration(iterator)
  File "D:\Program Files\anaconda\envs\myenv\lib\site-packages\gradio\utils.py", line 514, in async_iteration
    return await iterator.__anext__()
  File "D:\Program Files\anaconda\envs\myenv\lib\site-packages\gradio\utils.py", line 640, in asyncgen_wrapper
    response = await iterator.__anext__()
  File "D:\Program Files\anaconda\envs\myenv\lib\site-packages\gradio\chat_interface.py", line 490, in _stream_fn
    first_response = await async_iteration(generator)
  File "D:\Program Files\anaconda\envs\myenv\lib\site-packages\gradio\utils.py", line 514, in async_iteration
    return await iterator.__anext__()
  File "D:\Program Files\anaconda\envs\myenv\lib\site-packages\gradio\utils.py", line 507, in __anext__
    return await anyio.to_thread.run_sync(
  File "D:\Program Files\anaconda\envs\myenv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "D:\Program Files\anaconda\envs\myenv\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "D:\Program Files\anaconda\envs\myenv\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "D:\Program Files\anaconda\envs\myenv\lib\site-packages\gradio\utils.py", line 490, in run_sync_iterator_async
    return next(iterator)
  File "D:\Graduate\LLM\meet-libai\qa\interaction.py", line 18, in chat_libai
    answers = get_answer(message, history)
  File "D:\Graduate\LLM\meet-libai\qa\answer.py", line 25, in get_answer
    entities = check_entity(question)
  File "D:\Graduate\LLM\meet-libai\qa\question_parser.py", line 43, in check_entity
    code, msg, results = search(question)
  File "D:\Graduate\LLM\meet-libai\model\graph_entity\search_service.py", line 14, in search
    results, msg = INSTANCE.search(query)
  File "D:\Program Files\anaconda\envs\myenv\lib\site-packages\multipledispatch\dispatcher.py", line 439, in __call__
    return func(self.obj, *args, **kwargs)
  File "D:\Graduate\LLM\meet-libai\model\graph_entity\search_model.py", line 164, in search
    INSTANCE.reload()
  File "D:\Graduate\LLM\meet-libai\model\graph_entity\search_model.py", line 77, in reload
    self._load_model_info(version)
  File "D:\Graduate\LLM\meet-libai\model\model_base.py", line 184, in _load_model_info
    raise ModelLoadError("model info file not found")
model.model_error.ModelLoadError: Failed to load model: model info file not found

**Comment by BinNong** [comment]
要先构建rag文档向量索引，然后才能使用
